(in-package :utils)

(defun isalnum (char)
  (alphanumericp char))
(defun isalpha (char)
  (alpha-char-p char))
(defun iscntrl (char))
(defun isdigit (char)
  (digit-char-p char))
(defun islower (char)
  (lower-case-p char))
(defun isgraph (char)
  (graphic-char-p char))
(defun isprint (char))
(defun ispunct (char))
(defun isspace (char)
  "Is CHAR a whitespace character (newline chars are also considered white)."
  (member char '(#\Space #\Tab #\Return #\Linefeed #\Newline #\Page)))
(defun isupper (char)
  (upper-case-p char))
(defun isxdigit (char)
  (digit-char-p char 16))
